version: '3'
services:
  browser:
    
    #use for Apple Silicon
    #image: seleniarm/standalone-chromium

    # Chrome is crashing for me so I'm using firefox for now
    image: seleniarm/standalone-firefox
    
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
      - "7900:7900" #for web VNC access

  ruby:
    build: .
    volumes:
      - .:/app
    depends_on: 
      - browser
    environment: 
      - SELENIUM_HOST=browser
      - SELENIUM_PORT=4444

